version: "3.9"
services:
  db:
    image: postgres:14.1
    container_name: "bibliotheque-db"
    environment:
      POSTGRES_DB: bibliotheque-db
      POSTGRES_PASSWORD: pwd
    ports:
      - "5432:5432"
    volumes:
      - ./.dev/db/schema.sql:/docker-entrypoint-initdb.d/init.sql
