= Sommaire

== link:authentification/README.adoc[Authentification]

=== Stratégie de tests

==== Tests d'un RestController

Utilisation de `@WebMvcTest` pour pouvoir tester la couche _Controller_ composée du `RestController` (en incluant l'URL mapping, la sérialisation/dé-sérialisation) et du `ControllerAdvice`.
On utilise l'annotation `@MockBean` pour mocker les appels aux services métiers.

NOTE: Voir la classe UserControllerTest

==== Tests de Repository / adapter de repository

Pour tester seulement la couche d'accès aux données, on utilise `@DataJpaTest`.
On l'associe à un fichier properties `application-dataJpaTest` pour configurer une base de données h2 qui permettra aux tests d'être exécutés rapidement.

Si l'on veut tester l'ensemble de l'adapter du Repository, il va falloir un peu plus charger la conf Spring.

==== Tests du métier

Tests unitaires sur un ensemble de beans Spring avec `@ContextConfiguration`

==== Tests d'intégration complets

==== Tests du modèle

Pojo testing avec `openpojo` pour s'assurer que nos beans sont bien construits.

== link:securite/README.adoc[Sécurité]

* link:securite/README.adoc[Sécurisation simplifiée d'une API avec un token JWT]

== link:livre/README.adoc[Livre]

* Tests d'architecture avec `ArchUnit`
