CREATE SEQUENCE "PUBLIC".seq_role
  INCREMENT BY 1
  START WITH 1;

CREATE SEQUENCE "PUBLIC".seq_utilisateur
  INCREMENT BY 1
  START WITH 1;

CREATE SEQUENCE "PUBLIC".seq_utilisateur_role
  INCREMENT BY 1
  START WITH 1;

CREATE TABLE "PUBLIC"."ROLE"(
 ID BIGINT PRIMARY KEY NOT NULL,
 ROLE_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE "PUBLIC"."UTILISATEUR"(
 ID BIGINT PRIMARY KEY NOT NULL,
 LOGIN VARCHAR(100) NOT NULL,
 PASSWORD VARCHAR(100) NOT NULL
);


CREATE TABLE "PUBLIC"."UTILISATEUR_ROLE"(
 ID BIGINT PRIMARY KEY NOT NULL,
 USER_ID BIGINT NOT NULL,
 ROLE_ID BIGINT NOT NULL
);