server:
  port: 8092

spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        default_schema: livre
  datasource:
    url: jdbc:postgresql://localhost:5432/bibliotheque-db
    username: postgres
    password: pwd
  liquibase:
    default-schema: livre
