server:
  port: 8092

spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/bibliotheque-livre-db
    username: postgres
    password: pwd

bibliotheque:
  authentification:
    url: http://localhost:8091

jwt:
  secret: lJXtk18CBKOyMxuLDZj1ACQqM4jdLTUAIUNng3PmLLbRSPbAraqdGzzDEazFYIZql1MsgHYHVIkUpkjhJcs0EOcGiBdJtsmJXssO

securite:
  authentification:
    listeBlanche:
      - '/authenticate'
      - '/swagger-ui.html'
      - '/swagger-resources/**'
      - '/v2/api-docs'
      - '/webjars/**'
