server:
  port: 8092

bibliotheque:
  authentification:
    url: http://localhost:8091

jwt:
  secret: lJXtk18CBKOyMxuLDZj1ACQqM4jdLTUAIUNng3PmLLbRSPbAraqdGzzDEazFYIZql1MsgHYHVIkUpkjhJcs0EOcGiBdJtsmJXssO
