version: "3.9"
services:
  db:
    image: postgres:14.1
    container_name: "bibliotheque-livre-db"
    environment:
      POSTGRES_DB: bibliotheque-livre-db
      POSTGRES_PASSWORD: pwd
    ports:
      - "5432:5432"
