name: Java CI

on:
    push:
    schedule:
        -   cron: 0 8 * * 0-6

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout branche
                uses: actions/checkout@master

            -   name: Set up JDK 11
                uses: actions/setup-java@master
                with:
                    java-version: 11

            -   name: Build
                run: mvn clean install -DskipTests

            -   name: Unit Tests
                run: mvn surefire:test -DtestFailureIgnore=true

            -   name: Integration Tests
                run: mvn failsafe:integration-test -DskipAfterFailureCount=999

            -   name: Sonar Analysis
                env:
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                    GITHUB_USERNAME: x-access-token
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: mvn --settings .github/workflows/config/settings.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent package failsafe:integration-test sonar:sonar
