name: Publishing

on:
    push:
        tags: release/*

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout branche
                uses: actions/checkout@master

            -   name: Set up JDK 11
                uses: actions/setup-java@master
                with:
                    java-version: 11

            -   name: Build
                run: mvn clean install -DskipTests

            -   name: Unit & Integration Tests
                run: mvn surefire:test -DtestFailureIgnore=true failsafe:integration-test -DskipAfterFailureCount=999

            -   name: Sonar Analysis
                env:
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                    GITHUB_USERNAME: x-access-token
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: mvn --settings .github/workflows/config/settings.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent package failsafe:integration-test sonar:sonar

            #https://stackoverflow.com/questions/57711558/deploy-to-github-package-registry-from-github-action
            -   name: Publish
                env:
                    GITHUB_USERNAME: x-access-token
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: mvn --settings .github/workflows/config/settings.xml deploy
